from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter(tags=['admin-ui'])
PAGE = r'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>X1 Admin</title><style>
body{font-family:system-ui,sans-serif;margin:0;background:#f6f7f9;color:#151515}header{padding:18px 24px;background:#111;color:#fff;display:flex;gap:12px;align-items:center}main{max-width:1280px;margin:auto;padding:24px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px}.card{background:#fff;border:1px solid #ddd;border-radius:12px;padding:16px}input,button{padding:10px;border:1px solid #bbb;border-radius:8px}button{cursor:pointer;margin-right:8px}table{width:100%;border-collapse:collapse;background:#fff}td,th{padding:10px;border-bottom:1px solid #eee;text-align:left;font-size:13px;vertical-align:top}.muted{color:#666}.stable{color:#08752b}.degraded{color:#9a6700}.failed,.critical{color:#b42318}.unknown{color:#667085}.pill{font-weight:700}.wide{overflow:auto}</style></head><body><header><b>X1 Admin Console</b><span>Control Plane</span></header><main>
<div class="card"><b>Авторизация</b><p class="muted">Токен хранится только в sessionStorage текущей вкладки.</p><input id="token" type="password" style="width:min(700px,90%)"><button onclick="save()">Открыть</button><span id="auth"></span></div>
<h2>Контрольные точки системы</h2><div class="card"><button onclick="loadHealth(false)">Быстрая проверка</button><button onclick="loadHealth(true)">Глубокая проверка</button><span class="muted">Проверяет модули, миграции, backup и критические связки между ними.</span></div><div id="health" class="grid"></div><div id="roots"></div><div id="checkpoints" class="wide"></div>
<h2>Система</h2><div id="overview" class="grid"></div><h2>Экономика и ресурсы</h2><div id="economics" class="grid"></div><div id="resources" class="grid"></div><h2>Изображения</h2><div id="images" class="grid"></div><h2>Агенты разработки</h2><div id="agents" class="grid"></div><h2>Производительность</h2><div class="card"><button onclick="snapshot()">Снять метрики за 60 минут</button></div><div id="performance"></div><h2>Сигналы проблем пользователей</h2><div id="frustration"></div><h2>Безопасность</h2><div id="safety"></div><h2>Поисковые провайдеры</h2><div id="providers"></div><h2>Пользователи</h2><div id="users"></div><h2>Проблемы качества</h2><div id="audits"></div>
</main><script>
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));function save(){sessionStorage.x1AdminToken=document.getElementById('token').value;load()}async function api(path,opts={}){let t=sessionStorage.x1AdminToken||'';let r=await fetch(path,{...opts,headers:{...(opts.headers||{}),'Authorization':'Bearer '+t,'Content-Type':'application/json'}});if(!r.ok)throw new Error(r.status+' '+await r.text());return r.status===204?null:r.json()}function cards(o){return Object.entries(o||{}).map(([k,v])=>`<div class="card"><div class="muted">${esc(k)}</div><b>${esc(v)}</b></div>`).join('')}function tbl(rows,cols){if(!rows||!rows.length)return '<div class="card muted">Нет данных</div>';return '<table><tr>'+cols.map(c=>'<th>'+esc(c[0])+'</th>').join('')+'</tr>'+rows.map(r=>'<tr>'+cols.map(c=>'<td>'+esc(r[c[1]])+'</td>').join('')+'</tr>').join('')+'</table>'}function status(v){return `<span class="pill ${esc(v)}">${esc(v)}</span>`}async function snapshot(){await api('/v1/admin/performance/snapshots?window_minutes=60',{method:'POST'});await load()}
function paintHealth(h){document.getElementById('health').innerHTML=cards({status:h.status,score:h.score,stable:h.stable,degraded:h.degraded,critical:h.critical??h.failed,unknown:h.unknown??0});document.getElementById('roots').innerHTML=(h.root_causes||[]).length?'<div class="card critical"><b>Корневые причины:</b> '+esc((h.root_causes||[]).join(', '))+'</div>':'';let rows=(h.checkpoints||h.checks||[]).map(x=>({...x,status_view:status(x.status),action:x.recommended_action||((x.details||{}).recommended_action)||'',root:x.root_cause||((x.details||{}).root_cause)||''}));if(!rows.length){document.getElementById('checkpoints').innerHTML='<div class="card muted">Нет данных</div>';return}document.getElementById('checkpoints').innerHTML='<table><tr><th>Контур</th><th>Модуль</th><th>Статус</th><th>Зависит от</th><th>Корневая причина</th><th>Сообщение</th><th>Что делать</th><th>Сбоев подряд</th><th>Последняя проверка</th></tr>'+rows.map(x=>`<tr><td>${esc(x.key)}</td><td>${esc(x.subsystem)}</td><td>${x.status_view}</td><td>${esc(x.dependency)}</td><td>${esc(x.root)}</td><td>${esc(x.message)}</td><td>${esc(x.action)}</td><td>${esc(x.consecutive_failures)}</td><td>${esc(x.last_checked_at)}</td></tr>`).join('')+'</table>'}async function loadHealth(deep=false){let h=await api('/v1/admin/operations/health?refresh=true&deep='+(deep?'true':'false'));paintHealth(h)}
async function load(){try{document.getElementById('token').value=sessionStorage.x1AdminToken||'';let [o,u,p,a,se,fr,pm,ops,health]=await Promise.all([api('/v1/admin/overview'),api('/v1/admin/users?limit=50'),api('/v1/admin/search-providers'),api('/v1/admin/answer-audits?status=failed&limit=50'),api('/v1/admin/safety/events?state=new&limit=50'),api('/v1/admin/frustration/events?resolved=false&limit=50'),api('/v1/admin/performance/snapshots?limit=10'),api('/v1/admin/operations/summary?window_hours=24'),api('/v1/admin/operations/health?refresh=true')]);document.getElementById('auth').textContent=' ✓';paintHealth(health);document.getElementById('economics').innerHTML=cards(ops.economics);document.getElementById('resources').innerHTML=cards(ops.resources);document.getElementById('images').innerHTML=cards(ops.images);document.getElementById('agents').innerHTML=cards(ops.agents);document.getElementById('overview').innerHTML=cards(o);document.getElementById('performance').innerHTML=tbl(pm,[['Окно, мин','window_minutes'],['Запросы','request_count'],['P95 ответ, мс','p95_duration_ms'],['P95 очередь, мс','p95_queue_ms'],['CPU сек/успех','cpu_seconds_per_success'],['Контекст','context_efficiency_ratio'],['Frustration','frustration_count'],['Дата','created_at']]);document.getElementById('frustration').innerHTML=tbl(fr,[['Тип','kind'],['Severity','severity'],['User','user_id'],['Источник','source'],['Дата','created_at']]);document.getElementById('users').innerHTML=tbl(u,[['Email','email'],['Активен','is_active'],['Админ','is_admin'],['Тариф','plan']]);document.getElementById('safety').innerHTML=tbl(se,[['Severity','severity'],['Категория','category'],['Пользователь','user_id'],['Сигнал','summary'],['Дата','created_at']]);document.getElementById('providers').innerHTML=tbl(p,[['Провайдер','provider'],['Запросы','request_count'],['Успех','success_count'],['Ошибки','failure_count'],['Latency','last_latency_ms'],['Последняя ошибка','last_error']]);document.getElementById('audits').innerHTML=tbl(a,[['Request','request_id'],['User','user_id'],['Статус','status'],['Дата','created_at']])}catch(e){document.getElementById('auth').textContent=' '+e.message}}
if(sessionStorage.x1AdminToken)load();</script></body></html>'''
@router.get('/admin',response_class=HTMLResponse,include_in_schema=False)
def admin_console()->HTMLResponse:
    return HTMLResponse(PAGE,headers={'Cache-Control':'no-store','X-Frame-Options':'DENY','Content-Security-Policy':"default-src 'self'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'self'; frame-ancestors 'none'"})
