from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter(tags=["admin-ui"])

PAGE = r'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>X1 Admin</title><style>
body{font-family:system-ui,sans-serif;margin:0;background:#f6f7f9;color:#151515}header{padding:18px 24px;background:#111;color:#fff;display:flex;gap:12px;align-items:center}main{max-width:1200px;margin:auto;padding:24px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px}.card{background:#fff;border:1px solid #ddd;border-radius:12px;padding:16px}input,button{padding:10px;border:1px solid #bbb;border-radius:8px}button{cursor:pointer}table{width:100%;border-collapse:collapse;background:#fff}td,th{padding:10px;border-bottom:1px solid #eee;text-align:left;font-size:14px}.muted{color:#666}.bad{color:#a00}.ok{color:#08752b}</style></head>
<body><header><b>X1 Admin Console</b><span class="muted">Control Plane</span></header><main>
<div class="card"><b>Авторизация</b><p class="muted">Введите токен активной сессии администратора. Токен хранится только в sessionStorage текущей вкладки.</p><input id="token" type="password" style="width:min(700px,90%)"><button onclick="save()">Открыть</button><span id="auth"></span></div>
<h2>Система</h2><div id="overview" class="grid"></div><h2>Производительность</h2><div class="card"><button onclick="snapshot()">Снять метрики за 60 минут</button></div><div id="performance"></div><h2>Сигналы проблем пользователей</h2><div id="frustration"></div><h2>Безопасность и расследования</h2><div id="safety"></div><h2>Поисковые провайдеры</h2><div id="providers"></div><h2>Пользователи</h2><div id="users"></div><h2>Проблемы качества</h2><div id="audits"></div>
</main><script>
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function save(){sessionStorage.x1AdminToken=document.getElementById('token').value;load()}
async function api(path,opts={}){let t=sessionStorage.x1AdminToken||'';let r=await fetch(path,{...opts,headers:{...(opts.headers||{}),'Authorization':'Bearer '+t,'Content-Type':'application/json'}});if(!r.ok)throw new Error(r.status+' '+await r.text());return r.status===204?null:r.json()}
function cards(o){return Object.entries(o).map(([k,v])=>`<div class="card"><div class="muted">${esc(k)}</div><b>${esc(v)}</b></div>`).join('')}
function tbl(rows,cols){if(!rows.length)return '<div class="card muted">Нет данных</div>';return '<table><tr>'+cols.map(c=>'<th>'+esc(c[0])+'</th>').join('')+'</tr>'+rows.map(r=>'<tr>'+cols.map(c=>'<td>'+esc(r[c[1]])+'</td>').join('')+'</tr>').join('')+'</table>'}
async function snapshot(){try{await api('/v1/admin/performance/snapshots?window_minutes=60',{method:'POST'});await load()}catch(e){document.getElementById('auth').textContent=' '+e.message}}
async function load(){try{document.getElementById('token').value=sessionStorage.x1AdminToken||'';let [o,u,p,a,se,fr,pm]=await Promise.all([api('/v1/admin/overview'),api('/v1/admin/users?limit=50'),api('/v1/admin/search-providers'),api('/v1/admin/answer-audits?status=failed&limit=50'),api('/v1/admin/safety/events?state=new&limit=50'),api('/v1/admin/frustration/events?resolved=false&limit=50'),api('/v1/admin/performance/snapshots?limit=10')]);document.getElementById('auth').textContent=' ✓';document.getElementById('overview').innerHTML=cards(o);document.getElementById('performance').innerHTML=tbl(pm,[['Окно, мин','window_minutes'],['Запросы','request_count'],['P95 ответ, мс','p95_duration_ms'],['P95 очередь, мс','p95_queue_ms'],['CPU сек/успех','cpu_seconds_per_success'],['Контекст','context_efficiency_ratio'],['Frustration','frustration_count'],['Дата','created_at']]);document.getElementById('frustration').innerHTML=tbl(fr,[['Тип','kind'],['Severity','severity'],['User','user_id'],['Источник','source'],['Дата','created_at']]);document.getElementById('users').innerHTML=tbl(u,[['Email','email'],['Активен','is_active'],['Админ','is_admin'],['Тариф','plan']]);document.getElementById('safety').innerHTML=tbl(se,[['Severity','severity'],['Категория','category'],['Пользователь','user_id'],['Сигнал','summary'],['Дата','created_at']]);document.getElementById('providers').innerHTML=tbl(p,[['Провайдер','provider'],['Запросы','request_count'],['Успех','success_count'],['Ошибки','failure_count'],['Latency','last_latency_ms'],['Последняя ошибка','last_error']]);document.getElementById('audits').innerHTML=tbl(a,[['Request','request_id'],['User','user_id'],['Статус','status'],['Дата','created_at']])}catch(e){document.getElementById('auth').textContent=' '+e.message}}
if(sessionStorage.x1AdminToken)load();</script></body></html>'''

@router.get('/admin', response_class=HTMLResponse, include_in_schema=False)
def admin_console() -> HTMLResponse:
    return HTMLResponse(PAGE, headers={"Cache-Control": "no-store", "X-Frame-Options": "DENY", "Content-Security-Policy": "default-src 'self'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'self'; frame-ancestors 'none'"})
