from __future__ import annotations

import secrets

from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter(tags=["admin-user-ui"])

PAGE = r'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OLYA AI · Пользователи</title><style nonce="__NONCE__">
:root{--bg:#0a0b0d;--panel:#121419;--line:#292d34;--text:#f5f6f8;--muted:#9298a3;--ok:#67d39a;--warn:#efbd63;--bad:#ff8585;--accent:#c53d3e}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.5 Inter,system-ui,-apple-system,Segoe UI,Arial,sans-serif}button,input,select,textarea{font:inherit}.top{display:flex;gap:7px;align-items:center;padding:11px 14px;border-bottom:1px solid var(--line);position:sticky;top:0;background:#0a0b0df3;z-index:4}.top a,.btn{border:1px solid var(--line);background:#171a20;color:#fff;border-radius:9px;padding:8px 10px;text-decoration:none;cursor:pointer}.brand{font-weight:850}.grow{flex:1}.wrap{width:min(1180px,100%);margin:auto;padding:16px 12px 60px}.split{display:grid;grid-template-columns:340px minmax(0,1fr);gap:12px}.card{background:var(--panel);border:1px solid var(--line);border-radius:13px;padding:13px}.row{display:flex;gap:7px;align-items:center}.field{display:grid;gap:4px;margin-bottom:8px}.field label{font-size:11px;color:var(--muted)}.field input,.field select,.field textarea{width:100%;border:1px solid var(--line);background:#0f1115;color:#fff;border-radius:8px;padding:9px}.field textarea{min-height:70px;resize:vertical}.list{display:grid;gap:6px;margin-top:10px;max-height:70vh;overflow:auto}.user{border:1px solid transparent;background:#0f1115;color:#fff;border-radius:9px;padding:9px;text-align:left;cursor:pointer}.user:hover,.user.active{border-color:#545b66}.user b,.user span{display:block}.muted{color:var(--muted);font-size:12px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:8px}.metric{background:#0f1115;border-radius:10px;padding:10px}.metric span{display:block;color:var(--muted);font-size:11px}.metric b{display:block;font-size:16px;margin-top:2px}.section{margin-top:15px}.section h3{margin:0 0 8px;font-size:15px}.danger{border-color:#6d3030!important;color:#ffaaaa!important}.ok{color:var(--ok)}.bad{color:var(--bad)}@media(max-width:820px){.split{grid-template-columns:1fr}.list{max-height:300px}}
</style></head><body><header class="top"><div class="brand">OLYA AI · Пользователи</div><div class="grow"></div><a href="/admin">Главная</a><a href="/admin/users">Пользователи</a><a href="/admin/chats">Чаты</a></header><main class="wrap"><div class="split"><section class="card"><div class="row"><div class="field grow"><label>Поиск по email, имени или ID</label><input id="q"></div><button class="btn" id="find">Найти</button></div><div class="list" id="users"></div></section><section class="card"><div id="empty" class="muted">Выберите пользователя слева.</div><div id="details" hidden><div class="grid" id="summary"></div><div class="section"><h3>Тариф и лимиты</h3><div class="grid" id="quota"></div></div><div class="section"><h3>Ручное изменение лимитов</h3><div class="grid"><div class="field"><label>Тариф</label><select id="plan"><option value="">Не менять</option><option value="free">Free</option><option value="x1">X1</option><option value="pro">Pro</option><option value="max">Max</option><option value="business">Business</option></select></div><div class="field"><label>Вычислительный лимит в месяц, сек.</label><input id="monthly" type="number" min="0"></div><div class="field"><label>Одновременных ответов</label><input id="inference" type="number" min="1" max="32"></div><div class="field"><label>Причина изменения</label><input id="reason" value="Изменено владельцем"></div></div><button class="btn" id="save">Сохранить лимиты</button></div><div class="section"><h3>Управление аккаунтом</h3><div class="field"><label>Для опасного действия введите email пользователя</label><input id="confirm"></div><div class="row"><button class="btn" id="activate">Активировать</button><button class="btn danger" id="suspend">Приостановить</button><button class="btn danger" id="revoke">Завершить все сессии</button><button class="btn" id="chats">Открыть чаты</button></div></div><div class="section"><h3>Сессии</h3><div id="sessions" class="muted"></div></div><div class="muted section" id="status"></div></div></section></div></main><script nonce="__NONCE__">
const $=id=>document.getElementById(id),tok=()=>sessionStorage.getItem('x1AdminToken')||sessionStorage.getItem('x1_access_token')||'';let selected=null,version=0,current=null;
async function api(path,opts={}){const t=tok();if(!t)throw new Error('Нет admin token. Откройте сначала /admin.');const headers={...(opts.headers||{}),Authorization:'Bearer '+t};if(opts.body)headers['Content-Type']='application/json';const r=await fetch(path,{...opts,headers});let d=null;try{d=await r.json()}catch(_e){}if(!r.ok)throw new Error(typeof d?.detail==='string'?d.detail:'HTTP '+r.status);return d}
function metric(root,label,value,tone=''){const x=document.createElement('div');x.className='metric';const l=document.createElement('span');l.textContent=label;const v=document.createElement('b');v.className=tone;v.textContent=value===null||value===undefined?'—':String(value);x.append(l,v);root.append(x)}
async function search(){const rows=await api('/v1/admin/users/search?q='+encodeURIComponent($('q').value.trim())+'&limit=80'),root=$('users');root.replaceChildren();for(const row of rows){const b=document.createElement('button');b.className='user'+(row.id===selected?' active':'');const a=document.createElement('b');a.textContent=row.email;const m=document.createElement('span');m.className='muted';m.textContent=(row.display_name||'Без имени')+(row.is_active?'':' · ПРИОСТАНОВЛЕН')+(row.control_active?' · ручные лимиты':'');b.append(a,m);b.onclick=()=>openUser(row.id);root.append(b)}}
async function openUser(id){selected=id;const d=await api('/v1/admin/users/'+encodeURIComponent(id)+'/operations');current=d;$('empty').hidden=true;$('details').hidden=false;const s=$('summary');s.replaceChildren();metric(s,'Email',d.user.email);metric(s,'Имя',d.user.display_name||'—');metric(s,'Аккаунт',d.user.is_active?'Активен':'Приостановлен',d.user.is_active?'ok':'bad');metric(s,'Администратор',d.user.is_admin?'Да':'Нет');const q=$('quota');q.replaceChildren();metric(q,'Тариф',d.effective_quota.plan);metric(q,'Лимит вычислений',d.effective_quota.monthly_compute_seconds_limit+' сек.');metric(q,'Одновременных ответов',d.effective_quota.max_concurrent_inference);metric(q,'Одновременных задач',d.effective_quota.max_concurrent_jobs);version=d.control?.version||0;$('plan').value=d.control?.plan_override||'';$('monthly').value=d.control?.monthly_compute_seconds_limit??'';$('inference').value=d.control?.max_concurrent_inference??'';$('confirm').value='';$('sessions').textContent=(d.sessions||[]).map(x=>(x.active?'Активна':'Закрыта')+' · '+new Date(x.last_seen_at||x.created_at).toLocaleString('ru-RU')).join('\n')||'Сессий нет';$('status').textContent='Пользователь загружен';await search()}
async function save(){if(!selected)return;const body={expected_version:version,plan_override:$('plan').value||null,monthly_compute_seconds_limit:$('monthly').value===''?null:Number($('monthly').value),max_concurrent_inference:$('inference').value===''?null:Number($('inference').value),max_concurrent_jobs:null,expires_at:null,reason:$('reason').value.trim()||'Изменено владельцем'};await api('/v1/admin/users/'+selected+'/control',{method:'PUT',body:JSON.stringify(body)});await openUser(selected)}
async function state(active){if(!selected||!current)return;const body={is_active:active,confirm_email:$('confirm').value.trim(),reason:'Изменено владельцем'};await api('/v1/admin/users/'+selected+'/state',{method:'POST',body:JSON.stringify(body)});await openUser(selected)}
async function revoke(){if(!selected)return;await api('/v1/admin/users/'+selected+'/sessions/revoke',{method:'POST',body:JSON.stringify({confirm_email:$('confirm').value.trim(),reason:'Завершено владельцем'})});await openUser(selected)}
$('find').onclick=()=>search().catch(e=>alert(e.message));$('q').onkeydown=e=>{if(e.key==='Enter')$('find').click()};$('save').onclick=()=>save().catch(e=>$('status').textContent=e.message);$('activate').onclick=()=>state(true).catch(e=>$('status').textContent=e.message);$('suspend').onclick=()=>state(false).catch(e=>$('status').textContent=e.message);$('revoke').onclick=()=>revoke().catch(e=>$('status').textContent=e.message);$('chats').onclick=()=>{if(selected)location.href='/admin/chats?user_id='+encodeURIComponent(selected)};search().catch(e=>{$('users').textContent=e.message});
</script></body></html>'''


@router.get('/admin/users', response_class=HTMLResponse, include_in_schema=False)
def admin_users_console() -> HTMLResponse:
    nonce = secrets.token_urlsafe(18)
    response = HTMLResponse(PAGE.replace('__NONCE__', nonce))
    response.headers.update({
        'Content-Security-Policy': "default-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'; " + f"style-src 'nonce-{nonce}'; script-src 'nonce-{nonce}'; connect-src 'self'",
        'Cache-Control': 'no-store', 'Pragma': 'no-cache', 'Referrer-Policy': 'no-referrer',
        'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY',
    })
    return response
