from __future__ import annotations

import secrets

from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter(tags=["admin-ui"])

PAGE = r'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>X1 Admin Control Center</title><style nonce="__NONCE__">
:root{--bg:#090b10;--panel:#111620;--panel2:#151b25;--line:#29313d;--text:#f4f6fa;--muted:#94a0b1;--ok:#65d392;--warn:#efbd63;--bad:#ff8080;--accent:#d34747}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.5 Inter,system-ui,-apple-system,Segoe UI,Arial,sans-serif}button,input{font:inherit}.top{position:sticky;top:0;z-index:5;background:rgba(9,11,16,.96);border-bottom:1px solid var(--line);padding:12px max(14px,calc((100% - 1220px)/2));display:flex;align-items:center;gap:10px;flex-wrap:wrap}.brand{font-weight:850;letter-spacing:.04em}.spacer{flex:1}.nav{display:flex;gap:6px;flex-wrap:wrap}.nav a,.btn{border:1px solid var(--line);border-radius:9px;padding:8px 11px;color:#e8edf5;background:#171d27;text-decoration:none;cursor:pointer}.btn.primary{background:var(--accent);border-color:transparent;font-weight:750}.btn:disabled{opacity:.5;cursor:default}.wrap{width:min(1220px,100%);margin:auto;padding:20px 16px 64px}.auth{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center}.auth input{min-width:0;background:#0d1219;color:#fff;border:1px solid var(--line);border-radius:9px;padding:10px}.section{margin-top:22px}.section-head{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-bottom:10px}.section-head h2{margin:0;font-size:17px}.muted{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px}.card{border:1px solid var(--line);background:var(--panel);border-radius:13px;padding:14px;min-width:0}.card .label{color:var(--muted);font-size:12px}.card .value{font-size:20px;font-weight:800;overflow-wrap:anywhere}.ok{color:var(--ok)}.warn{color:var(--warn)}.bad{color:var(--bad)}.status{display:inline-flex;border:1px solid var(--line);border-radius:999px;padding:3px 8px;font-size:12px}.wide{overflow:auto;border:1px solid var(--line);border-radius:12px;background:var(--panel)}table{width:100%;border-collapse:collapse;min-width:680px}th,td{padding:9px 10px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top;font-size:12px}th{color:var(--muted);font-weight:650;background:#0e131b}.notice{padding:11px 12px;border:1px solid var(--line);border-radius:10px;background:var(--panel2);margin-top:8px}.toolbar{display:flex;gap:7px;flex-wrap:wrap}.empty{padding:18px;color:var(--muted)}.gap-top{margin-top:10px}@media(max-width:680px){.wrap{padding:14px 10px 50px}.top{padding:10px}.auth{grid-template-columns:1fr}.auth .btn{width:100%}.grid{grid-template-columns:repeat(2,minmax(0,1fr))}.card .value{font-size:17px}.nav{width:100%;overflow:auto;flex-wrap:nowrap}.nav a{white-space:nowrap}.section{margin-top:18px}}@media(max-width:420px){.grid{grid-template-columns:1fr}}
</style></head><body><header class="top"><div class="brand">X1 Admin · Control Center</div><div class="spacer"></div><nav class="nav"><a href="/admin/beta">Beta</a><a href="/admin/launch">Launch</a><a href="/admin/media">Media</a></nav></header><main class="wrap">
<section class="card"><div class="auth"><input id="token" type="password" autocomplete="off" placeholder="Admin Bearer token"><button class="btn primary" id="connect">Открыть Control Center</button></div><div class="muted" id="auth-state">Токен хранится только в sessionStorage этой вкладки.</div></section>
<section class="section"><div class="section-head"><h2>Операционный статус</h2><div class="toolbar"><button class="btn" id="refresh">Обновить</button><button class="btn" id="deep-check">Глубокая проверка</button><button class="btn" id="snapshot">Снять performance snapshot</button></div><span class="muted" id="updated"></span></div><div class="grid" id="headline"></div></section>
<section class="section"><div class="section-head"><h2>Сигналы и блокеры</h2></div><div class="grid" id="signals"></div><div id="release-note"></div><div class="wide" id="blockers"></div></section>
<section class="section"><div class="section-head"><h2>Трафик и экономика</h2></div><div class="grid" id="traffic"></div><div class="grid gap-top" id="economics"></div></section>
<section class="section"><div class="section-head"><h2>Billing и API</h2></div><div class="grid" id="billing"></div><div class="grid gap-top" id="api"></div></section>
<section class="section"><div class="section-head"><h2>Нагрузка и ресурсы</h2></div><div class="grid" id="resources"></div><div class="wide gap-top" id="overload"></div></section>
<section class="section"><div class="section-head"><h2>Health checkpoints</h2></div><div class="grid" id="health-summary"></div><div class="wide" id="health-table"></div></section>
<section class="section"><div class="section-head"><h2>Последние performance snapshots</h2></div><div class="wide" id="performance"></div></section>
<section class="section"><div class="section-head"><h2>Административный audit trail</h2></div><div class="wide" id="audit"></div></section>
</main><script nonce="__NONCE__">
const $=id=>document.getElementById(id);const tokenInput=$('token');tokenInput.value=sessionStorage.getItem('x1AdminToken')||'';
function fmt(v){if(v===null||v===undefined)return '—';if(typeof v==='number')return Number.isInteger(v)?v.toLocaleString('ru-RU'):v.toLocaleString('ru-RU',{maximumFractionDigits:3});if(typeof v==='boolean')return v?'Да':'Нет';return String(v)}
function human(k){return String(k||'').replaceAll('_',' ')}
async function api(path,opts={}){const token=sessionStorage.getItem('x1AdminToken')||'';if(!token)throw new Error('Введите admin token');const headers={...(opts.headers||{}),Authorization:'Bearer '+token};if(opts.body)headers['Content-Type']='application/json';const r=await fetch(path,{...opts,headers,credentials:'omit'});let data=null;try{data=await r.json()}catch(_e){}if(r.status===401||r.status===403)throw new Error('Admin token недействителен или недостаточно прав');if(!r.ok)throw new Error((data&&data.detail)||('HTTP '+r.status));return data}
function clear(root){root.replaceChildren()}
function card(label,value,tone=''){const el=document.createElement('div');el.className='card';const l=document.createElement('div');l.className='label';l.textContent=human(label);const v=document.createElement('div');v.className='value '+tone;v.textContent=fmt(value);el.append(l,v);return el}
function renderMap(id,obj,tones={}){const root=$(id);clear(root);for(const [k,v] of Object.entries(obj||{})){if(v&&typeof v==='object')continue;root.append(card(k,v,tones[k]||''))}if(!root.childNodes.length)root.append(card('status','Нет данных','warn'))}
function table(id,rows,cols){const root=$(id);clear(root);if(!rows||!rows.length){const e=document.createElement('div');e.className='empty';e.textContent='Нет данных';root.append(e);return}const t=document.createElement('table'),head=document.createElement('tr');for(const [label] of cols){const th=document.createElement('th');th.textContent=label;head.append(th)}t.append(head);for(const row of rows){const tr=document.createElement('tr');for(const [,key] of cols){const td=document.createElement('td');td.textContent=fmt(row&&row[key]);tr.append(td)}t.append(tr)}root.append(t)}
function renderHeadline(cc,health,release){const root=$('headline');clear(root);const releaseReady=Boolean(release&&release.ready_for_public_release),healthStatus=String(health&&health.status||'unknown');root.append(card('release',releaseReady?'READY':'BLOCKED',releaseReady?'ok':'bad'));root.append(card('health',healthStatus,healthStatus==='stable'?'ok':healthStatus==='unknown'?'warn':'bad'));root.append(card('users',cc.accounts&&cc.accounts.users));root.append(card('active users',cc.accounts&&cc.accounts.active_users));root.append(card('requests / window',cc.traffic&&cc.traffic.requests));root.append(card('queue p95 ms',cc.traffic&&cc.traffic.p95_queue_ms,Number(cc.traffic&&cc.traffic.p95_queue_ms||0)>5000?'warn':''));root.append(card('open complaints',cc.signals&&cc.signals.open_complaints,Number(cc.signals&&cc.signals.open_complaints||0)?'warn':'ok'));root.append(card('release regressions',cc.signals&&cc.signals.release_blocking_regressions,Number(cc.signals&&cc.signals.release_blocking_regressions||0)?'bad':'ok'))}
function renderSignals(cc,release){renderMap('signals',cc.signals||{},Object.fromEntries(Object.keys(cc.signals||{}).map(k=>[k,Number(cc.signals[k]||0)?(k.includes('release')||k.includes('safety')?'bad':'warn'):'ok'])));const note=$('release-note');clear(note);const n=document.createElement('div');n.className='notice '+(release.ready_for_public_release?'ok':'bad');n.textContent=release.ready_for_public_release?'Release gate зелёный.':'Release заблокирован: '+Number((release.blockers||[]).length)+' blocker(s).';note.append(n);table('blockers',release.blockers||[],[['Checkpoint','key'],['Статус','status'],['Причина','message'],['Корень','root_cause'],['Действие','recommended_action']])}
function renderOverload(data){const rows=Object.entries(data||{}).map(([name,x])=>({name,...x}));table('overload',rows,[['Lane','name'],['Active','active'],['Waiting','waiting'],['Max active','max_concurrent'],['Max queue','max_queue'],['Breaker','breaker_state'],['Failures','breaker_failures']])}
function renderHealth(health){renderMap('health-summary',{status:health.status,score:health.score,stable:health.stable,degraded:health.degraded,critical:health.critical??health.failed,unknown:health.unknown});const rows=(health.checkpoints||health.checks||[]).filter(x=>x.status!=='stable').slice(0,40);table('health-table',rows,[['Контур','key'],['Статус','status'],['Сообщение','message'],['Root cause','root_cause'],['Проверено','last_checked_at']])}
async function load(deep=false){$('auth-state').textContent='Загружаю…';try{const health=await api('/v1/admin/operations/health?refresh=true&deep='+(deep?'true':'false'));const [cc,release,perf,audit]=await Promise.all([api('/v1/admin/operations/control-center?window_hours=24'),api('/v1/admin/reliability/release-readiness?refresh=false'),api('/v1/admin/performance/snapshots?limit=8'),api('/v1/admin/audit-log?limit=20')]);renderHeadline(cc,health,release);renderSignals(cc,release);renderMap('traffic',cc.traffic||{});renderMap('economics',cc.economics||{});renderMap('billing',cc.billing||{});renderMap('api',cc.api||{});renderMap('resources',cc.resources||{});renderOverload(cc.overload||{});renderHealth(health);table('performance',perf,[['Окно, мин','window_minutes'],['Запросы','request_count'],['Success','success_count'],['P95, мс','p95_duration_ms'],['P95 queue','p95_queue_ms'],['CPU sec/success','cpu_seconds_per_success'],['Frustration','frustration_count'],['Дата','created_at']]);table('audit',audit,[['Действие','action'],['Target','target_type'],['Target ID','target_id'],['Actor','actor_user_id'],['Дата','created_at']]);$('updated').textContent='Обновлено '+new Date(cc.generated_at).toLocaleString('ru-RU');$('auth-state').textContent='Control Center подключён.'}catch(e){$('auth-state').textContent=e.message}}
$('connect').onclick=()=>{sessionStorage.setItem('x1AdminToken',tokenInput.value.trim());load(false)};$('refresh').onclick=()=>load(false);$('deep-check').onclick=()=>load(true);$('snapshot').onclick=async()=>{try{await api('/v1/admin/performance/snapshots?window_minutes=60',{method:'POST'});await load(false)}catch(e){$('auth-state').textContent=e.message}};if(sessionStorage.getItem('x1AdminToken'))load(false);
</script></body></html>'''


@router.get('/admin', response_class=HTMLResponse, include_in_schema=False)
def admin_console() -> HTMLResponse:
    nonce = secrets.token_urlsafe(18)
    response = HTMLResponse(PAGE.replace('__NONCE__', nonce))
    response.headers.update({
        'Content-Security-Policy': (
            "default-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'; "
            f"style-src 'nonce-{nonce}'; script-src 'nonce-{nonce}'; connect-src 'self'"
        ),
        'Cache-Control': 'no-store',
        'Pragma': 'no-cache',
        'Referrer-Policy': 'no-referrer',
        'X-Content-Type-Options': 'nosniff',
        'X-Frame-Options': 'DENY',
        'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=()',
    })
    return response
