from __future__ import annotations

import secrets

from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter(tags=["admin-chat-ui"])

PAGE = r'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OLYA AI · Чаты пользователей</title><style nonce="__NONCE__">
:root{--bg:#0a0b0d;--panel:#121419;--line:#292d34;--text:#f4f5f7;--muted:#9298a3;--accent:#c53d3e}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.45 Inter,system-ui,-apple-system,Segoe UI,Arial,sans-serif}button,input{font:inherit}.top{position:sticky;top:0;z-index:5;display:flex;align-items:center;gap:8px;padding:11px 16px;border-bottom:1px solid var(--line);background:#0a0b0df2}.brand{font-weight:800}.grow{flex:1}.btn,.top a{border:1px solid var(--line);background:#171a20;color:#fff;border-radius:9px;padding:8px 10px;text-decoration:none;cursor:pointer}.wrap{height:calc(100vh - 59px);display:grid;grid-template-columns:360px minmax(0,1fr)}.side{border-right:1px solid var(--line);min-height:0;display:grid;grid-template-rows:auto auto 1fr}.filter{padding:8px 12px 0;color:#d7dbe2;font-size:12px}.filter button{margin-left:6px;border:0;background:transparent;color:#aaa;cursor:pointer}.search{padding:12px;border-bottom:1px solid var(--line);display:flex;gap:7px}.search input{width:100%;min-width:0;border:1px solid var(--line);background:#0f1115;color:#fff;border-radius:9px;padding:9px}.list{overflow:auto;padding:8px}.chat{width:100%;display:block;text-align:left;border:0;background:transparent;color:var(--text);padding:10px;border-radius:10px;cursor:pointer}.chat:hover,.chat.active{background:#171a20}.chat b{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.meta,.preview{display:block;color:var(--muted);font-size:11px;margin-top:2px}.preview{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.main{min-width:0;display:grid;grid-template-rows:auto 1fr}.head{padding:14px 18px;border-bottom:1px solid var(--line)}.head h1{margin:0 0 3px;font-size:18px}.messages{overflow:auto;padding:18px max(16px,calc((100% - 900px)/2))}.msg{margin:0 0 18px}.role{font-size:11px;color:var(--muted);margin-bottom:4px}.bubble{white-space:pre-wrap;overflow-wrap:anywhere;font-size:15px;line-height:1.58}.user .bubble{background:#1a1d23;border-radius:14px;padding:10px 12px}.assistant .bubble{padding:2px 0}.empty{color:var(--muted);padding:24px}@media(max-width:800px){.wrap{grid-template-columns:1fr}.side{position:absolute;inset:59px 18% 0 0;z-index:4;background:var(--bg)}.side.hidden{display:none}.main{grid-column:1}.mobile{display:inline-block!important}}.mobile{display:none}
</style></head><body><header class="top"><div class="brand">OLYA AI · Админка</div><a href="/admin">Главная</a><a href="/admin/users">Пользователи</a><a href="/admin/chats">Чаты</a><div class="grow"></div><button class="btn mobile" id="toggle">Список</button></header><div class="wrap"><aside class="side" id="side"><div class="filter" id="filter" hidden></div><div class="search"><input id="q" placeholder="Email, имя или название чата"><button class="btn" id="find">Найти</button></div><div class="list" id="list"></div></aside><main class="main"><div class="head" id="head"><h1>Чаты пользователей</h1><div class="meta">Выберите чат слева.</div></div><div class="messages" id="messages"><div class="empty">Здесь можно видеть, что пользователи пишут OLYA AI и какие ответы получают.</div></div></main></div><script nonce="__NONCE__">
const $=id=>document.getElementById(id),token=()=>sessionStorage.getItem('x1AdminToken')||sessionStorage.getItem('x1_access_token')||'',params=new URLSearchParams(location.search);let selected='',userFilter=params.get('user_id')||'';
async function api(path){const t=token();if(!t)throw new Error('Нет admin token. Сначала откройте /admin и авторизуйтесь.');const r=await fetch(path,{headers:{Authorization:'Bearer '+t}});let d=null;try{d=await r.json()}catch(_e){}if(!r.ok)throw new Error(typeof d?.detail==='string'?d.detail:'HTTP '+r.status);return d}
function dt(v){return v?new Date(v).toLocaleString('ru-RU'):''}
function filterUI(){const f=$('filter');if(!userFilter){f.hidden=true;f.replaceChildren();return}f.hidden=false;f.replaceChildren();const s=document.createElement('span');s.textContent='Показываю чаты выбранного пользователя';const b=document.createElement('button');b.type='button';b.textContent='× сбросить';b.onclick=()=>{userFilter='';history.replaceState(null,'','/admin/chats');filterUI();load().catch(e=>alert(e.message))};f.append(s,b)}
async function load(){filterUI();const q=encodeURIComponent($('q').value.trim()),uid=userFilter?'&user_id='+encodeURIComponent(userFilter):'',rows=await api('/v1/admin/chat-observer/conversations?limit=120&q='+q+uid),root=$('list');root.replaceChildren();if(!rows.length){const e=document.createElement('div');e.className='empty';e.textContent='Чаты не найдены';root.append(e);return}for(const c of rows){const b=document.createElement('button');b.className='chat'+(c.id===selected?' active':'');const title=document.createElement('b');title.textContent=c.title||'Новый чат';const meta=document.createElement('span');meta.className='meta';meta.textContent=(c.display_name||c.email||'Пользователь')+' · '+c.message_count+' сообщ. · '+dt(c.updated_at);const p=document.createElement('span');p.className='preview';p.textContent=c.last_message||'';b.append(title,meta,p);b.onclick=()=>openChat(c.id);root.append(b)}}
async function openChat(id){selected=id;const d=await api('/v1/admin/chat-observer/conversations/'+encodeURIComponent(id)+'/messages?limit=300'),c=d.conversation,head=$('head');head.replaceChildren();const h=document.createElement('h1');h.textContent=c.title||'Новый чат';const m=document.createElement('div');m.className='meta';m.textContent=(c.display_name||c.email||'Пользователь')+' · '+c.email+' · обновлён '+dt(c.updated_at);head.append(h,m);const root=$('messages');root.replaceChildren();for(const row of d.messages){const box=document.createElement('div');box.className='msg '+(row.role==='user'?'user':'assistant');const role=document.createElement('div');role.className='role';role.textContent=(row.role==='user'?'Пользователь':'OLYA AI')+' · '+dt(row.created_at);const bubble=document.createElement('div');bubble.className='bubble';bubble.textContent=row.content;box.append(role,bubble);root.append(box)}root.scrollTop=root.scrollHeight;await load();if(innerWidth<800)$('side').classList.add('hidden')}
$('find').onclick=()=>load().catch(e=>alert(e.message));$('q').onkeydown=e=>{if(e.key==='Enter')$('find').click()};$('toggle').onclick=()=>$('side').classList.toggle('hidden');load().catch(e=>{$('list').innerHTML='<div class="empty">'+e.message+'</div>'});
</script></body></html>'''


@router.get('/admin/chats', response_class=HTMLResponse, include_in_schema=False)
def admin_chats() -> HTMLResponse:
    nonce = secrets.token_urlsafe(18)
    response = HTMLResponse(PAGE.replace('__NONCE__', nonce))
    response.headers.update({
        'Content-Security-Policy': "default-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'; " + f"style-src 'nonce-{nonce}'; script-src 'nonce-{nonce}'; connect-src 'self'",
        'Cache-Control': 'no-store', 'Pragma': 'no-cache', 'Referrer-Policy': 'no-referrer',
        'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY',
    })
    return response
