from __future__ import annotations

import secrets

from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter(tags=["admin-user-ui"])

PAGE = r'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>X1 Admin · Users</title><style nonce="__NONCE__">
:root{--bg:#090b10;--panel:#111620;--line:#29313d;--text:#f4f6fa;--muted:#94a0b1;--ok:#65d392;--warn:#efbd63;--bad:#ff8080;--accent:#d34747}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.5 Inter,system-ui,-apple-system,Segoe UI,Arial,sans-serif}button,input,select,textarea{font:inherit}.top{position:sticky;top:0;z-index:4;padding:12px max(14px,calc((100% - 1180px)/2));display:flex;gap:9px;align-items:center;flex-wrap:wrap;background:#090b10f5;border-bottom:1px solid var(--line)}.top a,.btn{border:1px solid var(--line);border-radius:9px;padding:8px 11px;background:#171d27;color:#eef2f8;text-decoration:none;cursor:pointer}.brand{font-weight:850}.grow{flex:1}.wrap{width:min(1180px,100%);margin:auto;padding:18px 14px 60px}.card{background:var(--panel);border:1px solid var(--line);border-radius:13px;padding:14px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:10px}.split{display:grid;grid-template-columns:minmax(280px,.8fr) minmax(0,1.6fr);gap:12px}.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.field{display:grid;gap:5px}.field label{color:var(--muted);font-size:12px}.field input,.field select,.field textarea{width:100%;min-width:0;padding:9px;border:1px solid var(--line);border-radius:8px;background:#0c1118;color:var(--text)}.field textarea{min-height:72px;resize:vertical}.muted{color:var(--muted)}.ok{color:var(--ok)}.warn{color:var(--warn)}.bad{color:var(--bad)}h2,h3{margin:0 0 10px}.section{margin-top:16px}.list{display:grid;gap:7px}.user{padding:10px;border:1px solid var(--line);border-radius:9px;background:#0e131b;cursor:pointer}.user:hover{border-color:#596579}.user b,.user span{display:block;overflow-wrap:anywhere}.wide{overflow:auto;border:1px solid var(--line);border-radius:10px}table{width:100%;border-collapse:collapse;min-width:650px}th,td{padding:8px 9px;border-bottom:1px solid var(--line);text-align:left;font-size:12px;vertical-align:top}th{color:var(--muted)}.danger{border-color:#7d3333}.primary{background:var(--accent);border-color:transparent;font-weight:750}.status{min-height:22px;margin-top:8px}.actions{display:grid;grid-template-columns:1fr 1fr;gap:10px}.hidden{display:none}@media(max-width:820px){.split{grid-template-columns:1fr}.actions{grid-template-columns:1fr}.top{padding:10px}.wrap{padding:12px 10px 50px}}@media(max-width:480px){.grid{grid-template-columns:1fr}.row .btn{width:100%}}
</style></head><body><header class="top"><div class="brand">X1 Admin · Users</div><div class="grow"></div><a href="/admin">Control Center</a><a href="/admin/beta">Beta</a><a href="/admin/launch">Launch</a></header><main class="wrap">
<section class="card"><div class="row"><div class="field grow"><label>Admin Bearer token</label><input id="token" type="password" autocomplete="off"></div><button class="btn primary" id="connect">Подключить</button></div><div class="status muted" id="global-status">Токен хранится только в sessionStorage этой вкладки.</div></section>
<div class="split section"><section class="card"><h2>Пользователи</h2><div class="row"><div class="field grow"><label>Поиск по email, имени или ID</label><input id="search" autocomplete="off"></div><button class="btn" id="search-btn">Найти</button></div><div class="list section" id="users"></div></section>
<section class="card" id="details"><h2>Операции</h2><div class="muted" id="empty">Выберите пользователя.</div><div id="workspace" class="hidden">
<div class="grid" id="summary"></div>
<div class="section"><h3>Billing и effective quota</h3><div class="grid" id="quota"></div></div>
<div class="section"><h3>Policy override</h3><div class="grid"><div class="field"><label>Plan override</label><select id="plan"><option value="">Не переопределять</option><option value="free">Free</option><option value="x1">X1</option><option value="pro">Pro</option><option value="max">Max</option><option value="business">Business</option></select></div><div class="field"><label>Monthly compute seconds</label><input id="monthly" type="number" min="0" max="31536000"></div><div class="field"><label>Max concurrent inference</label><input id="inference" type="number" min="1" max="32"></div><div class="field"><label>Max concurrent jobs</label><input id="jobs" type="number" min="1" max="32"></div><div class="field"><label>Expires at (ISO, пусто = без срока)</label><input id="expires" autocomplete="off"></div><div class="field"><label>Причина</label><textarea id="override-reason" maxlength="500"></textarea></div></div><div class="row section"><button class="btn primary" id="save-control">Сохранить override</button><span class="muted" id="control-version"></span></div></div>
<div class="actions section"><div class="card danger"><h3>Состояние аккаунта</h3><div class="field"><label>Подтвердите email пользователя</label><input id="state-confirm" autocomplete="off"></div><div class="field"><label>Причина</label><textarea id="state-reason" maxlength="500"></textarea></div><div class="row section"><button class="btn" id="activate">Активировать</button><button class="btn danger" id="suspend">Приостановить и отозвать сессии</button></div></div><div class="card danger"><h3>Сессии / очистка override</h3><div class="field"><label>Подтвердите email пользователя</label><input id="danger-confirm" autocomplete="off"></div><div class="field"><label>Причина</label><textarea id="danger-reason" maxlength="500"></textarea></div><div class="row section"><button class="btn danger" id="revoke">Отозвать все сессии</button><button class="btn danger" id="clear-control">Снять override</button></div></div></div>
<div class="section"><h3>Сессии</h3><div class="wide" id="sessions"></div></div><div class="section"><h3>Audit trail пользователя</h3><div class="wide" id="audit"></div></div>
</div></section></div></main><script nonce="__NONCE__">
const $=id=>document.getElementById(id);let selected=null;let controlVersion=0;const token=$('token');token.value=sessionStorage.getItem('x1AdminToken')||'';
function text(v){return v===null||v===undefined||v===''?'—':String(v)}function clear(el){el.replaceChildren()}function val(id){const x=$(id).value.trim();return x===''?null:x}function num(id){const x=val(id);return x===null?null:Number(x)}
async function api(path,opts={}){const t=sessionStorage.getItem('x1AdminToken')||'';if(!t)throw new Error('Введите admin token');const headers={...(opts.headers||{}),Authorization:'Bearer '+t};if(opts.body)headers['Content-Type']='application/json';const r=await fetch(path,{...opts,headers,credentials:'omit'});let data=null;try{data=await r.json()}catch(_e){}if(r.status===401||r.status===403)throw new Error('Недостаточно прав или token недействителен');if(!r.ok)throw new Error(typeof data?.detail==='string'?data.detail:'HTTP '+r.status);return data}
function card(label,value,tone=''){const el=document.createElement('div');el.className='card';const l=document.createElement('div');l.className='muted';l.textContent=label;const v=document.createElement('b');v.className=tone;v.textContent=text(value);el.append(l,v);return el}
function table(id,rows,cols){const root=$(id);clear(root);if(!rows?.length){const e=document.createElement('div');e.className='muted';e.textContent='Нет данных';root.append(e);return}const t=document.createElement('table'),h=document.createElement('tr');for(const [label] of cols){const th=document.createElement('th');th.textContent=label;h.append(th)}t.append(h);for(const row of rows){const tr=document.createElement('tr');for(const [,key] of cols){const td=document.createElement('td');td.textContent=text(row[key]);tr.append(td)}t.append(tr)}root.append(t)}
async function search(){try{const q=encodeURIComponent($('search').value.trim());const rows=await api('/v1/admin/users/search?q='+q+'&limit=50');const root=$('users');clear(root);for(const row of rows){const el=document.createElement('div');el.className='user';const b=document.createElement('b');b.textContent=row.email;const s=document.createElement('span');s.className='muted';s.textContent=(row.display_name||'')+' · '+row.id+(row.is_active?'':' · SUSPENDED')+(row.control_active?' · OVERRIDE':'');el.append(b,s);el.addEventListener('click',()=>openUser(row.id));root.append(el)}if(!rows.length){const e=document.createElement('div');e.className='muted';e.textContent='Ничего не найдено';root.append(e)}}catch(e){$('global-status').textContent=e.message}}
async function openUser(id){try{selected=id;const d=await api('/v1/admin/users/'+encodeURIComponent(id)+'/operations');$('empty').classList.add('hidden');$('workspace').classList.remove('hidden');const s=$('summary');clear(s);s.append(card('Email',d.user.email),card('Имя',d.user.display_name),card('Account',d.user.is_active?'ACTIVE':'SUSPENDED',d.user.is_active?'ok':'bad'),card('Admin',d.user.is_admin?'Да':'Нет'));const q=$('quota');clear(q);q.append(card('Effective plan',d.effective_quota.plan),card('Monthly compute',d.effective_quota.monthly_compute_seconds_limit),card('Inference concurrency',d.effective_quota.max_concurrent_inference),card('Job concurrency',d.effective_quota.max_concurrent_jobs),card('Billing plan',d.billing_subscription?.plan||'free'),card('Billing status',d.billing_subscription?.status||'none'));const c=d.control;controlVersion=c?.version||0;$('control-version').textContent='version '+controlVersion;$('plan').value=c?.plan_override||'';$('monthly').value=c?.monthly_compute_seconds_limit??'';$('inference').value=c?.max_concurrent_inference??'';$('jobs').value=c?.max_concurrent_jobs??'';$('expires').value=c?.expires_at||'';$('override-reason').value=c?.reason||'';$('state-confirm').value='';$('danger-confirm').value='';table('sessions',d.sessions||[],[['ID','id'],['Active','active'],['Created','created_at'],['Last seen','last_seen_at'],['Expires','expires_at'],['Revoked','revoked_at']]);table('audit',d.audit||[],[['Action','action'],['Actor','actor_user_id'],['Date','created_at']]);$('global-status').textContent='Пользователь загружен.'}catch(e){$('global-status').textContent=e.message}}
function ensureSelected(){if(!selected)throw new Error('Выберите пользователя')}
async function saveControl(){try{ensureSelected();const body={expected_version:controlVersion,plan_override:val('plan'),monthly_compute_seconds_limit:num('monthly'),max_concurrent_inference:num('inference'),max_concurrent_jobs:num('jobs'),expires_at:val('expires'),reason:$('override-reason').value.trim()};await api('/v1/admin/users/'+encodeURIComponent(selected)+'/control',{method:'PUT',body:JSON.stringify(body)});await openUser(selected)}catch(e){$('global-status').textContent=e.message}}
async function state(active){try{ensureSelected();const body={is_active:active,confirm_email:$('state-confirm').value.trim(),reason:$('state-reason').value.trim()};await api('/v1/admin/users/'+encodeURIComponent(selected)+'/state',{method:'POST',body:JSON.stringify(body)});await openUser(selected);await search()}catch(e){$('global-status').textContent=e.message}}
async function revoke(){try{ensureSelected();const body={confirm_email:$('danger-confirm').value.trim(),reason:$('danger-reason').value.trim()};await api('/v1/admin/users/'+encodeURIComponent(selected)+'/sessions/revoke',{method:'POST',body:JSON.stringify(body)});await openUser(selected)}catch(e){$('global-status').textContent=e.message}}
async function clearControl(){try{ensureSelected();const body={expected_version:controlVersion,confirm_email:$('danger-confirm').value.trim(),reason:$('danger-reason').value.trim()};await api('/v1/admin/users/'+encodeURIComponent(selected)+'/control/clear',{method:'POST',body:JSON.stringify(body)});await openUser(selected);await search()}catch(e){$('global-status').textContent=e.message}}
$('connect').addEventListener('click',()=>{sessionStorage.setItem('x1AdminToken',token.value.trim());search()});$('search-btn').addEventListener('click',search);$('search').addEventListener('keydown',e=>{if(e.key==='Enter')search()});$('save-control').addEventListener('click',saveControl);$('activate').addEventListener('click',()=>state(true));$('suspend').addEventListener('click',()=>state(false));$('revoke').addEventListener('click',revoke);$('clear-control').addEventListener('click',clearControl);if(sessionStorage.getItem('x1AdminToken'))search();
</script></body></html>'''


@router.get('/admin/users', response_class=HTMLResponse, include_in_schema=False)
def admin_users_console() -> HTMLResponse:
    nonce = secrets.token_urlsafe(18)
    response = HTMLResponse(PAGE.replace('__NONCE__', nonce))
    response.headers.update({
        'Content-Security-Policy': (
            "default-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'; "
            f"style-src 'nonce-{nonce}'; script-src 'nonce-{nonce}'; connect-src 'self'"
        ),
        'Cache-Control': 'no-store',
        'Pragma': 'no-cache',
        'Referrer-Policy': 'no-referrer',
        'X-Content-Type-Options': 'nosniff',
        'X-Frame-Options': 'DENY',
        'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=()',
    })
    return response
