from __future__ import annotations

"""Canonical, import-safe ORM registry.

Core tables are maintained by hand; migration-derived tables are regenerated by
``scripts/generate_orm_models.py``. Sprint extensions remain explicit so every
runtime imports one complete SQLAlchemy metadata graph.
"""

from app.models_core import *  # noqa: F401,F403
from app.models_migrations import *  # noqa: F401,F403
from app.models_sprint27 import *  # noqa: F401,F403
from app.models_sprint29 import *  # noqa: F401,F403
from app.models_sprint30 import *  # noqa: F401,F403
from app.models_sprint31 import *  # noqa: F401,F403
from app.models_sprint37 import *  # noqa: F401,F403
from app.models_sprint38 import *  # noqa: F401,F403
from app.models_sprint45 import *  # noqa: F401,F403
from app.models_sprint51 import *  # noqa: F401,F403
from app.models_sprint53 import *  # noqa: F401,F403
from app.models_sprint59 import *  # noqa: F401,F403
from app.models_sprint61 import *  # noqa: F401,F403
from app.models_sprint62 import *  # noqa: F401,F403
from app.models_sprint69 import *  # noqa: F401,F403

# Successful canonical assistant/usage writes make the matching ChatRun
# terminal in the same flush, closing the restart window before transport ack.
import app.services.chat_run_atomicity  # noqa: F401,E402
