from __future__ import annotations

import secrets

from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter(tags=["support-ui"])

_BASE_STYLE = """
:root{--bg:#090b10;--panel:#111620;--line:#29313d;--text:#f4f6fa;--muted:#94a0b1;--ok:#65d392;--warn:#efbd63;--bad:#ff8080;--accent:#d34747}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.5 Inter,system-ui,-apple-system,Segoe UI,Arial,sans-serif}button,input,select,textarea{font:inherit}.top{position:sticky;top:0;z-index:3;background:#090b10f5;border-bottom:1px solid var(--line);padding:12px max(14px,calc((100% - 1080px)/2));display:flex;gap:8px;align-items:center}.top a{color:var(--text);text-decoration:none;border:1px solid var(--line);border-radius:9px;padding:8px 11px}.brand{font-weight:850}.grow{flex:1}.wrap{width:min(1080px,100%);margin:auto;padding:18px 14px 60px}.grid{display:grid;grid-template-columns:340px 1fr;gap:14px}.card{background:var(--panel);border:1px solid var(--line);border-radius:13px;padding:14px}.stack{display:grid;gap:9px}.muted{color:var(--muted)}input,select,textarea{width:100%;background:#0c1118;color:var(--text);border:1px solid var(--line);border-radius:9px;padding:10px}textarea{min-height:120px;resize:vertical}button{border:1px solid var(--line);border-radius:9px;padding:9px 12px;background:#171d27;color:#eef2f8;cursor:pointer}.primary{background:var(--accent);border-color:transparent;font-weight:750}.ticket{width:100%;text-align:left}.ticket.active{border-color:#667187}.ticket b{display:block}.meta{font-size:12px;color:var(--muted)}.messages{display:grid;gap:9px;max-height:52vh;overflow:auto;padding-right:3px}.msg{border:1px solid var(--line);border-radius:11px;padding:11px;background:#0e131a}.msg.admin{border-color:#4c596b}.msg .who{font-size:11px;text-transform:uppercase;letter-spacing:.06em;color:var(--muted)}.msg .body{white-space:pre-wrap;overflow-wrap:anywhere;margin-top:5px}.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.row>*{flex:1}.status{min-height:22px;color:var(--muted);margin-top:8px}.empty{padding:28px;text-align:center;color:var(--muted)}@media(max-width:760px){.grid{grid-template-columns:1fr}.top{padding:10px}.wrap{padding:12px 10px 45px}.messages{max-height:none}.row>*{min-width:100%}}
"""


def _response(title: str, body: str, script: str) -> HTMLResponse:
    nonce = secrets.token_urlsafe(18)
    page = f'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><style nonce="{nonce}">{_BASE_STYLE}</style></head><body>{body}<script nonce="{nonce}">{script}</script></body></html>'''
    response = HTMLResponse(page)
    response.headers.update({
        "Content-Security-Policy": f"default-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'; style-src 'nonce-{nonce}'; script-src 'nonce-{nonce}'; connect-src 'self'",
        "Cache-Control": "no-store",
        "Pragma": "no-cache",
        "Referrer-Policy": "no-referrer",
        "X-Content-Type-Options": "nosniff",
        "X-Frame-Options": "DENY",
    })
    return response


@router.get("/support", response_class=HTMLResponse, include_in_schema=False)
def support_page() -> HTMLResponse:
    body = '''<header class="top"><div class="brand">X1 · Поддержка</div><div class="grow"></div><a href="/app">← В X1</a></header><main class="wrap"><div class="grid"><section class="stack"><div class="card"><h2>Новое обращение</h2><p class="muted">Тикет сохраняет историю вопроса и ответов. Не отправляйте пароли, API-ключи и платёжные реквизиты.</p><input id="subject" maxlength="180" placeholder="Коротко опишите вопрос"><select id="category"><option value="general">Общий вопрос</option><option value="technical">Техническая проблема</option><option value="billing">Оплата и тариф</option><option value="account">Аккаунт</option><option value="quality">Качество ответа</option><option value="api">API</option></select><textarea id="message" maxlength="8000" placeholder="Что произошло, что ожидали и что получили"></textarea><button class="primary" id="create">Создать тикет</button><div class="status" id="create-status"></div></div><div class="stack" id="tickets"></div></section><section class="card"><div id="detail" class="empty">Выберите обращение слева.</div></section></div></main>'''
    script = r'''
const $=id=>document.getElementById(id);const token=sessionStorage.getItem('x1_access_token')||'';let selected=null;
if(!token)location.replace('/login');
async function api(path,opts={}){const h={...(opts.headers||{}),Authorization:'Bearer '+token};if(opts.body)h['Content-Type']='application/json';const r=await fetch(path,{...opts,headers:h,credentials:'omit'});let d=null;try{d=await r.json()}catch{}if(r.status===401||r.status===403){sessionStorage.removeItem('x1_access_token');location.replace('/login');throw new Error('Требуется вход')}if(!r.ok)throw new Error(typeof d?.detail==='string'?d.detail:(d?.detail?.message||'HTTP '+r.status));return d}
function el(tag,text,cls=''){const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e}
async function load(){const rows=await api('/v1/support/tickets');const root=$('tickets');root.replaceChildren();if(!rows.length){root.append(el('div','Обращений пока нет.','card muted'));return}for(const t of rows){const b=el('button',undefined,'ticket'+(selected===t.id?' active':''));b.append(el('b',t.subject),el('div',t.status+' · '+t.category+' · '+new Date(t.updated_at).toLocaleString('ru-RU'),'meta'));b.onclick=()=>openTicket(t.id);root.append(b)}}
async function openTicket(id){selected=id;await load();const t=await api('/v1/support/tickets/'+encodeURIComponent(id));const root=$('detail');root.replaceChildren();const head=el('div');head.append(el('h2',t.subject),el('div',t.status+' · '+t.category+' · приоритет '+t.priority,'meta'));root.append(head);const msgs=el('div',undefined,'messages');for(const m of t.messages){const x=el('div',undefined,'msg '+(m.author_role==='admin'?'admin':''));x.append(el('div',m.author_role==='admin'?'Поддержка X1':'Вы','who'),el('div',m.body,'body'),el('div',new Date(m.created_at).toLocaleString('ru-RU'),'meta'));msgs.append(x)}root.append(msgs);if(t.status!=='closed'){const box=el('textarea');box.maxLength=8000;box.placeholder='Написать ответ…';const row=el('div',undefined,'row');const send=el('button','Отправить','primary');const close=el('button','Закрыть тикет');send.onclick=async()=>{if(!box.value.trim())return;send.disabled=true;try{await api('/v1/support/tickets/'+encodeURIComponent(id)+'/messages',{method:'POST',body:JSON.stringify({message:box.value.trim()})});await openTicket(id)}catch(e){alert(e.message)}finally{send.disabled=false}};close.onclick=async()=>{await api('/v1/support/tickets/'+encodeURIComponent(id)+'/close',{method:'POST'});await openTicket(id)};row.append(send,close);root.append(box,row)}}
$('create').onclick=async()=>{const b=$('create');b.disabled=true;$('create-status').textContent='Создаю…';try{const t=await api('/v1/support/tickets',{method:'POST',body:JSON.stringify({subject:$('subject').value.trim(),category:$('category').value,message:$('message').value.trim()})});$('subject').value='';$('message').value='';selected=t.id;$('create-status').textContent='Тикет создан.';try{window.x1MetrikaGoal&&window.x1MetrikaGoal('support_ticket_created')}catch{}await openTicket(t.id)}catch(e){$('create-status').textContent=e.message}finally{b.disabled=false}};
load().catch(e=>$('create-status').textContent=e.message);
'''
    return _response("Поддержка — X1 AI", body, script)


@router.get("/admin/support", response_class=HTMLResponse, include_in_schema=False)
def admin_support_page() -> HTMLResponse:
    body = '''<header class="top"><div class="brand">X1 Admin · Support</div><div class="grow"></div><a href="/admin">Control Center</a></header><main class="wrap"><div class="card"><div class="row"><input id="token" type="password" autocomplete="off" placeholder="Admin Bearer token"><select id="filter"><option value="">Все статусы</option><option value="open">open</option><option value="waiting_admin">waiting_admin</option><option value="in_progress">in_progress</option><option value="waiting_user">waiting_user</option><option value="resolved">resolved</option><option value="closed">closed</option></select><button class="primary" id="connect">Открыть</button></div><div class="status" id="status">Токен хранится только в sessionStorage этой вкладки.</div></div><div class="grid" style="margin-top:14px"><section class="stack" id="tickets"></section><section class="card"><div id="detail" class="empty">Выберите тикет.</div></section></div></main>'''
    script = r'''
const $=id=>document.getElementById(id);$('token').value=sessionStorage.getItem('x1AdminToken')||'';let selected=null;
async function api(path,opts={}){const t=sessionStorage.getItem('x1AdminToken')||'';if(!t)throw new Error('Введите admin token');const h={...(opts.headers||{}),Authorization:'Bearer '+t};if(opts.body)h['Content-Type']='application/json';const r=await fetch(path,{...opts,headers:h,credentials:'omit'});let d=null;try{d=await r.json()}catch{}if(!r.ok)throw new Error(typeof d?.detail==='string'?d.detail:'HTTP '+r.status);return d}function el(tag,text,cls=''){const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e}
async function load(){const q=$('filter').value?'?status='+encodeURIComponent($('filter').value):'';const rows=await api('/v1/admin/support/tickets'+q);const root=$('tickets');root.replaceChildren();if(!rows.length){root.append(el('div','Нет тикетов.','card muted'));return}for(const t of rows){const b=el('button',undefined,'ticket'+(selected===t.id?' active':''));b.append(el('b',t.subject),el('div',(t.user_email||t.user_id)+' · '+t.status+' · '+t.priority,'meta'));b.onclick=()=>openTicket(t.id);root.append(b)}$('status').textContent='Тикетов: '+rows.length}
async function openTicket(id){selected=id;await load();const t=await api('/v1/admin/support/tickets/'+encodeURIComponent(id));const root=$('detail');root.replaceChildren();root.append(el('h2',t.subject),el('div',(t.user_email||t.user_id)+' · '+t.category,'meta'));const controls=el('div',undefined,'row');const st=el('select');for(const v of ['open','in_progress','waiting_user','waiting_admin','resolved','closed']){const o=el('option',v);o.value=v;o.selected=v===t.status;st.append(o)}const pr=el('select');for(const v of ['low','normal','high','urgent']){const o=el('option',v);o.value=v;o.selected=v===t.priority;pr.append(o)}const save=el('button','Сохранить статус');save.onclick=async()=>{await api('/v1/admin/support/tickets/'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({status:st.value,priority:pr.value})});await openTicket(id)};controls.append(st,pr,save);root.append(controls);const msgs=el('div',undefined,'messages');for(const m of t.messages){const x=el('div',undefined,'msg '+(m.author_role==='admin'?'admin':''));x.append(el('div',m.author_role==='admin'?'Админ':'Клиент','who'),el('div',m.body,'body'),el('div',new Date(m.created_at).toLocaleString('ru-RU'),'meta'));msgs.append(x)}root.append(msgs);if(t.status!=='closed'){const box=el('textarea');box.maxLength=8000;box.placeholder='Ответ клиенту…';const send=el('button','Ответить','primary');send.onclick=async()=>{if(!box.value.trim())return;send.disabled=true;try{await api('/v1/admin/support/tickets/'+encodeURIComponent(id)+'/messages',{method:'POST',body:JSON.stringify({message:box.value.trim()})});await openTicket(id)}catch(e){$('status').textContent=e.message}finally{send.disabled=false}};root.append(box,send)}}
$('connect').onclick=()=>{sessionStorage.setItem('x1AdminToken',$('token').value.trim());load().catch(e=>$('status').textContent=e.message)};$('filter').onchange=()=>load().catch(e=>$('status').textContent=e.message);if(sessionStorage.getItem('x1AdminToken'))load().catch(e=>$('status').textContent=e.message);
'''
    return _response("X1 Admin · Support", body, script)
