from __future__ import annotations

import secrets

from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter(tags=["user-workspace"])


@router.get("/app", response_class=HTMLResponse, include_in_schema=False)
def workspace() -> HTMLResponse:
    nonce = secrets.token_urlsafe(18)
    document = '''<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>X1 — рабочее пространство</title>
<style nonce="__NONCE__">
:root{--bg:#090b10;--side:#0e1118;--card:#131821;--line:#252b36;--text:#f4f6fa;--muted:#9aa5b4;--accent:#d34747;--ok:#66d394;--warn:#f0bf66;--bad:#ff8383}
*{box-sizing:border-box}html,body{height:100%}body{margin:0;background:var(--bg);color:var(--text);font:15px/1.5 Inter,system-ui,-apple-system,Segoe UI,Arial,sans-serif;overflow:hidden}
button,select,textarea{font:inherit}button{cursor:pointer}.shell{height:100%;display:grid;grid-template-columns:270px 1fr}aside{background:var(--side);border-right:1px solid var(--line);padding:16px;display:flex;flex-direction:column;min-width:0}.brand{font-weight:850;letter-spacing:.08em;padding:8px 4px 18px}.new{width:100%;padding:11px;border:1px solid var(--line);background:#181d27;color:#fff;border-radius:11px;font-weight:700}.history{overflow:auto;margin:14px -5px;flex:1;padding:0 5px}.conv{width:100%;text-align:left;border:0;background:transparent;color:#dfe4ec;padding:10px;border-radius:9px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.conv:hover,.conv.active{background:#1b202a}.account{border-top:1px solid var(--line);padding-top:12px;color:var(--muted);font-size:13px}.account-row{display:flex;justify-content:space-between;gap:8px;align-items:center}.linkbtn{background:transparent;border:0;color:#d7dce5;padding:5px}
main{min-width:0;display:flex;flex-direction:column;height:100%}header{height:62px;border-bottom:1px solid var(--line);display:flex;align-items:center;gap:10px;padding:0 18px}select{background:#121720;color:#fff;border:1px solid var(--line);border-radius:9px;padding:8px 10px}.spacer{flex:1}.health{font-size:13px;color:var(--muted)}.messages{flex:1;overflow:auto;padding:28px max(20px,calc((100% - 850px)/2));scroll-behavior:smooth}.empty{max-width:720px;margin:16vh auto 0;text-align:center}.empty h1{font-size:42px;margin:0 0 8px;letter-spacing:-.04em}.empty p{color:var(--muted);font-size:17px}.msg{max-width:820px;margin:0 auto 22px}.role{font-size:12px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted);margin-bottom:7px}.bubble{white-space:pre-wrap;overflow-wrap:anywhere}.user .bubble{background:#171d27;border:1px solid var(--line);padding:13px 15px;border-radius:14px}.assistant .bubble{font-size:16px;line-height:1.65}.error .bubble{color:var(--bad)}.meta{font-size:12px;color:var(--muted);margin-top:8px;display:flex;gap:8px;flex-wrap:wrap}.badge{border:1px solid var(--line);border-radius:999px;padding:2px 8px}.badge.supported{color:var(--ok)}.badge.unverified{color:var(--warn)}.badge.failed{color:var(--bad)}
.composer-wrap{border-top:1px solid var(--line);padding:14px 20px 18px;background:linear-gradient(180deg,rgba(9,11,16,.8),#090b10)}.composer{max-width:850px;margin:auto;border:1px solid #303744;background:#121720;border-radius:16px;padding:11px}textarea{display:block;width:100%;resize:none;min-height:52px;max-height:190px;border:0;outline:0;background:transparent;color:#fff;padding:7px 8px}.composer-foot{display:flex;align-items:center;gap:9px;padding:4px}.send{margin-left:auto;background:var(--accent);color:white;border:0;border-radius:10px;padding:9px 16px;font-weight:750;min-width:104px}.send.stop{background:#8c3030}.send:disabled{opacity:.5;cursor:default}.state{font-size:12px;color:var(--muted);min-height:18px;max-width:850px;margin:7px auto 0}.mobile-menu{display:none}
@media(max-width:760px){.shell{grid-template-columns:1fr}aside{display:none;position:fixed;z-index:4;inset:0 26% 0 0;box-shadow:30px 0 80px #000}aside.open{display:flex}.mobile-menu{display:inline-block;background:transparent;border:1px solid var(--line);color:white;border-radius:8px;padding:6px 9px}header{padding:0 10px}.messages{padding:20px 14px}.composer-wrap{padding:10px}.empty h1{font-size:34px}}
</style></head><body>
<div class="shell"><aside id="side"><div class="brand">X1 AI</div><button class="new" id="new-chat">+ Новый чат</button><div class="history" id="history"></div><div class="account"><div id="who">Проверяем аккаунт…</div><div class="account-row"><span>Токен только в этой вкладке</span><button class="linkbtn" id="logout">Выйти</button></div></div></aside>
<main><header><button class="mobile-menu" id="menu">☰</button><select id="mode" title="Режим"><option value="auto">Авто</option><option value="fast">Fast</option><option value="work">Work</option><option value="deep">Deep</option></select><select id="verify" title="Проверка"><option value="auto">Проверка: авто</option><option value="strict">Проверка: строгая</option><option value="off">Проверка: выкл</option></select><select id="web" title="Поиск в интернете"><option value="auto">Интернет: авто</option><option value="always">Интернет: всегда</option><option value="off">Интернет: выкл</option></select><div class="spacer"></div><span class="health" id="health">● X1</span></header>
<div class="messages" id="messages"><div class="empty" id="empty"><h1>Чем помочь?</h1><p>Чат использует локальную Qwen. Для актуальных данных X1 может сначала найти и проверить источники в интернете.</p></div></div>
<div class="composer-wrap"><div class="composer"><textarea id="prompt" maxlength="200000" placeholder="Напишите сообщение…"></textarea><div class="composer-foot"><span class="health" id="counter"></span><button class="send" id="send">Отправить</button></div></div><div class="state" id="state"></div></div></main></div>
<script nonce="__NONCE__">
const token=sessionStorage.getItem('x1_access_token');if(!token)location.replace('/login');
const $=id=>document.getElementById(id);let conversationId=null,busy=false,activeController=null,stopRequested=false;const messages=$('messages'),state=$('state'),prompt=$('prompt'),send=$('send'),empty=$('empty');
const legacyChatEndpoint='/v1/chat';const streamChatEndpoint='/v1/chat/stream';
function detailOf(data,status){const d=data&&data.detail;if(typeof d==='string')return d;if(d&&typeof d.message==='string')return d.message;if(status===403)return 'Доступ к ИИ пока не открыт для этого аккаунта текущей волной запуска.';if(status===429)return 'Лимит или защитный контур временно остановил запрос. Повторите позже.';if(status===503)return 'X1 сейчас занят или один из локальных сервисов восстанавливается. Повторите запрос через несколько секунд.';return 'Запрос не выполнен.'}
async function api(path,options={},timeout=220000){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeout);try{const headers={...(options.headers||{}),'Authorization':'Bearer '+token};if(options.body)headers['Content-Type']='application/json';const r=await fetch(path,{...options,headers,credentials:'omit',signal:controller.signal});let data=null;try{data=await r.json()}catch(_e){}if(r.status===401){sessionStorage.removeItem('x1_access_token');location.replace('/login');throw new Error('Сессия завершена')}if(!r.ok){const e=new Error(detailOf(data,r.status));e.status=r.status;throw e}return data}catch(e){if(e.name==='AbortError')throw new Error('Сервис отвечает слишком долго. Запрос остановлен, чтобы интерфейс не зависал.');throw e}finally{clearTimeout(timer)}}
function attachMeta(box,meta){if(!meta)return;const old=box.querySelector('.meta');if(old)old.remove();const m=document.createElement('div');m.className='meta';if(meta.quality){const q=document.createElement('span');q.className='badge '+meta.quality;q.textContent='Качество: '+meta.quality;m.append(q)}if(meta.mode){const x=document.createElement('span');x.className='badge';x.textContent=meta.mode;m.append(x)}if(meta.sources){const x=document.createElement('span');x.className='badge supported';x.textContent='Источников: '+meta.sources;m.append(x)}if(meta.ttft!==null&&meta.ttft!==undefined){const x=document.createElement('span');x.className='badge';x.textContent='TTFT: '+Number(meta.ttft).toLocaleString('ru-RU')+' мс';m.append(x)}if(meta.tps!==null&&meta.tps!==undefined){const x=document.createElement('span');x.className='badge';x.textContent=Number(meta.tps).toFixed(1)+' ток/с';m.append(x)}if(meta.queue!==null&&meta.queue!==undefined){const x=document.createElement('span');x.className='badge';x.textContent='Очередь: '+Number(meta.queue).toLocaleString('ru-RU')+' мс';m.append(x)}if(m.childNodes.length)box.append(m)}
function add(role,text,meta=null){if(empty)empty.style.display='none';const box=document.createElement('div');box.className='msg '+role;const r=document.createElement('div');r.className='role';r.textContent=role==='user'?'Вы':'X1';const b=document.createElement('div');b.className='bubble';b.textContent=text;box.append(r,b);attachMeta(box,meta);messages.append(box);messages.scrollTop=messages.scrollHeight;return{box,bubble:b}}
function addError(text){add('error',text)}
function setBusy(value,text='',canStop=false){busy=value;prompt.disabled=value;send.disabled=value&&!canStop;send.textContent=canStop?'Стоп':'Отправить';send.classList.toggle('stop',canStop);state.textContent=text}
function stopActive(){if(!activeController)return;stopRequested=true;activeController.abort();state.textContent='Останавливаю генерацию…'}
async function ensureConversation(text){if(conversationId)return conversationId;const c=await api('/v1/conversations',{method:'POST',body:JSON.stringify({title:text.slice(0,100)})},30000);conversationId=c.id;await loadConversations();return conversationId}
async function research(text,force=false){state.textContent=force?'Ищу источники…':'Проверяю, нужны ли свежие данные…';const run=await api('/v1/research/runs',{method:'POST',body:JSON.stringify({question:text,intent:'general',max_results:10})},30000);const freshness=(run.plan&&run.plan.freshness)||'stable';if(!force&&freshness!=='current'){state.textContent='Свежий интернет-поиск для этого запроса не требуется.';return[];}state.textContent='Ищу свежие источники…';await api('/v1/research/runs/'+encodeURIComponent(run.id)+'/discover',{method:'POST'},60000);const collected=await api('/v1/research/runs/'+encodeURIComponent(run.id)+'/collect',{method:'POST',body:JSON.stringify({max_sources:3})},90000);const ids=(collected.sources||[]).map(x=>x.id).filter(Boolean).slice(0,3);if(!ids.length)throw new Error('Поиск не дал проверяемых источников. Я не буду незаметно подменять интернет-поиск ответом из памяти модели.');return ids}
function sseBlocks(buffer){const blocks=[];let index;while((index=buffer.indexOf('\n\n'))>=0){blocks.push(buffer.slice(0,index));buffer=buffer.slice(index+2)}return{blocks,buffer}}
function decodeSse(block){let event='message';const data=[];for(const line of block.split('\n')){if(line.startsWith('event:'))event=line.slice(6).trim();else if(line.startsWith('data:'))data.push(line.slice(5).trimStart())}if(!data.length)return null;try{return{event,data:JSON.parse(data.join('\n'))}}catch(_e){return null}}
async function streamChat(body,live){const controller=new AbortController();activeController=controller;stopRequested=false;setBusy(true,'X1 принял запрос. Ожидаю первый токен…',true);const headers={'Authorization':'Bearer '+token,'Content-Type':'application/json','Accept':'text/event-stream'};let result=null;try{const r=await fetch(streamChatEndpoint,{method:'POST',headers,credentials:'omit',body:JSON.stringify(body),signal:controller.signal});if(r.status===401){sessionStorage.removeItem('x1_access_token');location.replace('/login');throw new Error('Сессия завершена')}if(!r.ok){let data=null;try{data=await r.json()}catch(_e){}throw new Error(detailOf(data,r.status))}if(!r.body)throw new Error('Браузер не получил поток ответа.');const reader=r.body.getReader();const decoder=new TextDecoder();let buffer='';while(true){const part=await reader.read();if(part.done)break;buffer+=decoder.decode(part.value,{stream:true});buffer=buffer.replace(/\r\n/g,'\n');const parsed=sseBlocks(buffer);buffer=parsed.buffer;for(const raw of parsed.blocks){const item=decodeSse(raw);if(!item)continue;const data=item.data||{};if(item.event==='token'){live.bubble.textContent+=(typeof data.text==='string'?data.text:'');messages.scrollTop=messages.scrollHeight;state.textContent='X1 отвечает…'}else if(item.event==='replace'){live.bubble.textContent=typeof data.text==='string'?data.text:live.bubble.textContent;messages.scrollTop=messages.scrollHeight;state.textContent='Ответ скорректирован проверкой.'}else if(item.event==='heartbeat'){state.textContent=(data.queue_waiting>0?'Запрос ждёт безопасную очередь…':'X1 обрабатывает запрос…')}else if(item.event==='result'){result=data}else if(item.event==='error'){throw new Error(detailOf({detail:data.detail},data.status_code||500))}}}if(buffer.trim()){const item=decodeSse(buffer);if(item&&item.event==='result')result=item.data}if(!result)throw new Error('Поток завершился без финального результата.');return result}catch(e){if(e.name==='AbortError'&&stopRequested)return{cancelled:true};throw e}finally{activeController=null}}
async function submit(){if(busy)return;const text=prompt.value.trim();if(!text)return;prompt.value='';updateCounter();add('user',text);setBusy(true,'Готовлю запрос…',false);let live=null;try{const cid=await ensureConversation(text);const webMode=$('web').value;let sourceIds=[];if(webMode==='always')sourceIds=await research(text,true);else if(webMode==='auto')sourceIds=await research(text,false);live=add('assistant','');const data=await streamChat({messages:[{role:'user',content:text}],conversation_id:cid,mode:$('mode').value,verification:$('verify').value,research_source_ids:sourceIds},live);if(data.cancelled){state.textContent='Генерация остановлена. Уже полученный текст оставлен на экране.';if(!live.bubble.textContent)live.box.remove();return}live.bubble.textContent=data.text||live.bubble.textContent;const usage=data.usage||{};attachMeta(live.box,{quality:data.quality&&data.quality.status,mode:usage.mode,sources:sourceIds.length,ttft:usage.ttft_ms,tps:usage.tokens_per_second,queue:usage.queue_ms});const warnings=(data.quality&&data.quality.warnings)||[];const perf=[];if(usage.ttft_ms!==null&&usage.ttft_ms!==undefined)perf.push('TTFT '+Number(usage.ttft_ms).toLocaleString('ru-RU')+' мс');if(usage.tokens_per_second!==null&&usage.tokens_per_second!==undefined)perf.push(Number(usage.tokens_per_second).toFixed(1)+' ток/с');state.textContent=[...warnings,...perf].join(' · ');await loadConversations()}catch(e){if(live&&!live.bubble.textContent)live.box.remove();addError(e.message||'Ошибка запроса');state.textContent=''}finally{setBusy(false,state.textContent,false);prompt.focus()}}
async function loadConversations(){try{const rows=await api('/v1/conversations?limit=30',{},30000);const h=$('history');h.replaceChildren();for(const c of rows){const b=document.createElement('button');b.className='conv'+(c.id===conversationId?' active':'');b.textContent=c.title||'Новый чат';b.onclick=()=>openConversation(c.id);h.append(b)}}catch(_e){}}
async function openConversation(id){if(busy)return;conversationId=id;messages.replaceChildren();try{const rows=await api('/v1/conversations/'+encodeURIComponent(id)+'/messages?limit=100',{},30000);if(!rows.length){messages.append(empty);empty.style.display='block'}else for(const m of rows)add(m.role==='assistant'?'assistant':'user',m.content);await loadConversations();$('side').classList.remove('open')}catch(e){addError(e.message)}}
function newChat(){if(busy)return;conversationId=null;messages.replaceChildren();messages.append(empty);empty.style.display='block';state.textContent='';loadConversations();prompt.focus()}
function updateCounter(){$('counter').textContent=prompt.value.length?prompt.value.length.toLocaleString('ru-RU')+' символов':''}
$('new-chat').onclick=newChat;send.onclick=()=>activeController?stopActive():submit();prompt.addEventListener('input',()=>{updateCounter();prompt.style.height='auto';prompt.style.height=Math.min(190,prompt.scrollHeight)+'px'});prompt.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();if(!busy)submit()}});$('menu').onclick=()=>$('side').classList.toggle('open');
$('logout').onclick=async()=>{if(activeController)stopActive();try{await api('/v1/auth/logout',{method:'POST'},15000)}catch(_e){}sessionStorage.removeItem('x1_access_token');sessionStorage.removeItem('x1_user_id');location.replace('/login')};
(async()=>{try{const me=await api('/v1/auth/me',{},20000);$('who').textContent=me.display_name||me.email;$('health').textContent='● '+(me.display_name||'X1');await loadConversations();prompt.focus()}catch(e){state.textContent=e.message}})();
</script></body></html>'''.replace("__NONCE__", nonce)
    response = HTMLResponse(document)
    response.headers.update({
        "Content-Security-Policy": (
            "default-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'; "
            f"style-src 'nonce-{nonce}'; script-src 'nonce-{nonce}'; connect-src 'self'; img-src 'self' data:"
        ),
        "Cache-Control": "no-store",
        "Pragma": "no-cache",
        "Referrer-Policy": "no-referrer",
        "X-Content-Type-Options": "nosniff",
        "X-Frame-Options": "DENY",
        "Permissions-Policy": "camera=(), microphone=(), geolocation=(), payment=()",
        "Cross-Origin-Opener-Policy": "same-origin",
        "Cross-Origin-Resource-Policy": "same-origin",
    })
    return response
